name: Downgraded Release

on:
  push:
    tags:
      - '*'

jobs:
  downgrade_release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip ci')"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: 8.4
          coverage: none

      - uses: "ramsey/composer-install@v3"

      # downgrade /src to PHP 7.4
      - run: vendor/bin/rector process --config .build/rector-74.php --ansi
      - run: vendor/bin/ecs --fix --ansi
      - run: vendor/bin/phpcs -p ./src/ --standard=PHPCompatibility --runtime-set testVersion 7.4

      # copy PHP 7.4 composer
      - run: cp .build/composer-74.json composer.json

      # clear the dev files
      - run: rm -rf .build .docker .github tests vendor ecs.php phpcs.xml .gitattributes .gitignore codeception.dist.yml composer.lock examples.php rector.php

      # setup git user to avoid error "Author identity unknown: *** Please tell me who you are."
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      # publish to the same repository and overwrite the tag
      - name: "Tag Downgraded Code"
        run: |
          git add --all
          git commit -m "releases PHP 7.4 downgraded version --skip ci"
          git tag "${GITHUB_REF#refs/tags/}" -f
          git push origin "${GITHUB_REF#refs/tags/}" -f

    cleanup_on_failure:
      runs-on: ubuntu-latest
      needs: downgrade_release
      if: failure()
      steps:
        - uses: "actions/checkout@v4"
        - run: |
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
        - name: "Delete Tag and Release"
          run: |
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "Deleting tag ${TAG_NAME}"
            git tag -d "${TAG_NAME}"
            git push --delete origin "${TAG_NAME}"
            echo "Deleting release ${TAG_NAME}"
            gh release delete "${TAG_NAME}" --yes