name: Downgraded Release

on:
  push:
    tags:
      - '*'

jobs:
  downgrade_release:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: 8.3
          coverage: none

      - uses: "ramsey/composer-install@v3"

      # downgrade /src to PHP 7.4
      - run: vendor/bin/rector process --config build/rector-74.php --ansi
      - run: vendor/bin/ecs --fix --ansi

      # copy PHP 7.4 composer
      - run: cp build/composer-74.json composer.json

      # clear the dev files
      - run: rm -rf .build .docker .github tests ecs.php .gitattributes .gitignore codeception.dist.yml example.php rectors.php

      # publish to the same repository with a new tag
      - name: "Tag Downgraded Code"
        run: |
          git add --all
          git commit -m "releases PHP 7.4 downgraded version"
          git tag "${GITHUB_REF#refs/tags/}" -f
          git push origin "${GITHUB_REF#refs/tags/}" -f